Suite: loong13
CacheDir: ../cache
Source: http://loong13.debian.net/debian-loong64 SUITE main contrib
Source: http://loong13.debian.net/debian-loong64 SUITE-updates main contrib
Source: http://loong13.debian.net/debian-loong64-security SUITE-security main contrib
Install-Source: http://pve.loongfans.cn/ SUITE main
Architecture: loong64
Name: proxmox-mail-gateway-9.1-standard
Version: 9.1-1
Section: mail
Maintainer: Proxmox VE Loong64 <wukaiyang@loongfans.cn>
Infopage: https://www.proxmox.com/en/proxmox-mail-gateway/overview
Description: Proxmox Mail Gateway 9.1
 A full featured mail proxy for spam and virus filtering, optimized for
 container environment.
